In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import requests

In [59]:
url = "https://free-nba.p.rapidapi.com/stats"

querystring = {"page":"0","per_page":"100"}

headers = {
    'x-rapidapi-host': "free-nba.p.rapidapi.com",
    'x-rapidapi-key': "7d4ccbc25bmsh49d7ffce4bf360ap1abf2fjsn6e4b1323ce66"
    }

In [83]:
def datagrab():
    page_number = 1
    data = []
    while page_number <= 5:
        
        querystring = {"page":str(page_number),"per_page":"100"}
        response = requests.request("GET", url, headers=headers, params=querystring).json()
        data += (response["data"])
        page_number += 1
    return data

In [84]:
data = datagrab()

In [85]:
len(data)

500

In [86]:
from pandas.io.json import json_normalize
df = pd.json_normalize(data)

In [88]:
df

,id,ast,blk,dreb,fg3_pct,fg3a,fg3m,fg_pct,fga,fgm,...,player.position,player.team_id,player.weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name
0,1069008,0.0,1.0,2.0,0.200,5.0,1.0,0.333,9.0,3.0,...,G,3,215.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings
1,1069009,4.0,0.0,5.0,0.000,2.0,0.0,0.200,5.0,1.0,...,F,26,234.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings
2,1069010,4.0,1.0,5.0,0.000,0.0,0.0,0.667,6.0,4.0,...,C,7,240.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings
3,1069011,1.0,0.0,1.0,0.545,11.0,6.0,0.500,18.0,9.0,...,G,26,214.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings
4,1069012,8.0,1.0,5.0,0.000,2.0,0.0,0.400,10.0,4.0,...,G,26,175.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1069494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,2,260.0,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics
496,1069495,1.0,0.0,5.0,0.000,2.0,0.0,0.500,8.0,4.0,...,F,1,210.0,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks
497,1069496,3.0,0.0,8.0,0.500,2.0,1.0,0.714,7.0,5.0,...,F-C,1,235.0,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks
498,1069497,0.0,1.0,3.0,0.333,3.0,1.0,0.333,6.0,2.0,...,C,1,245.0,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks
499,1069498,7.0,0.0,2.0,0.400,10.0,4.0,0.389,18.0,7.0,...,G,1,190.0,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks